//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `whisperIced.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package jeremie.lohyer.whisperIced;

interface _Marker
{
}
