//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `whisperIced.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package jeremie.lohyer.whisperIced;

/** @hidden */
public class _TextSenderPrxI extends com.zeroc.Ice._ObjectPrxI implements TextSenderPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
