//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `whisperIced.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package jeremie.lohyer.whisperIced;

public interface SpeechReceiverPrx extends com.zeroc.Ice.ObjectPrx
{
    default void addClient(String address, String port)
    {
        addClient(address, port, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addClient(String address, String port, java.util.Map<String, String> context)
    {
        _iceI_addClientAsync(address, port, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addClientAsync(String address, String port)
    {
        return _iceI_addClientAsync(address, port, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addClientAsync(String address, String port, java.util.Map<String, String> context)
    {
        return _iceI_addClientAsync(address, port, context, false);
    }

    /**
     * @hidden
     * @param iceP_address -
     * @param iceP_port -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addClientAsync(String iceP_address, String iceP_port, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addClient", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_address);
                     ostr.writeString(iceP_port);
                 }, null);
        return f;
    }

    default void prepareUpload(int nbBlocs)
    {
        prepareUpload(nbBlocs, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void prepareUpload(int nbBlocs, java.util.Map<String, String> context)
    {
        _iceI_prepareUploadAsync(nbBlocs, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> prepareUploadAsync(int nbBlocs)
    {
        return _iceI_prepareUploadAsync(nbBlocs, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> prepareUploadAsync(int nbBlocs, java.util.Map<String, String> context)
    {
        return _iceI_prepareUploadAsync(nbBlocs, context, false);
    }

    /**
     * @hidden
     * @param iceP_nbBlocs -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_prepareUploadAsync(int iceP_nbBlocs, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "prepareUpload", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_nbBlocs);
                 }, null);
        return f;
    }

    default void upload(int blocId, byte[] data)
    {
        upload(blocId, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void upload(int blocId, byte[] data, java.util.Map<String, String> context)
    {
        _iceI_uploadAsync(blocId, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> uploadAsync(int blocId, byte[] data)
    {
        return _iceI_uploadAsync(blocId, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> uploadAsync(int blocId, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_uploadAsync(blocId, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_blocId -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_uploadAsync(int iceP_blocId, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "upload", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_blocId);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeechReceiverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SpeechReceiverPrx.class, _SpeechReceiverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeechReceiverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SpeechReceiverPrx.class, _SpeechReceiverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeechReceiverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SpeechReceiverPrx.class, _SpeechReceiverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SpeechReceiverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SpeechReceiverPrx.class, _SpeechReceiverPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SpeechReceiverPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SpeechReceiverPrx.class, _SpeechReceiverPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SpeechReceiverPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SpeechReceiverPrx.class, _SpeechReceiverPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SpeechReceiverPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SpeechReceiverPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SpeechReceiverPrx ice_adapterId(String newAdapterId)
    {
        return (SpeechReceiverPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SpeechReceiverPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SpeechReceiverPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SpeechReceiverPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SpeechReceiverPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SpeechReceiverPrx ice_invocationTimeout(int newTimeout)
    {
        return (SpeechReceiverPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SpeechReceiverPrx ice_connectionCached(boolean newCache)
    {
        return (SpeechReceiverPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SpeechReceiverPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SpeechReceiverPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SpeechReceiverPrx ice_secure(boolean b)
    {
        return (SpeechReceiverPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SpeechReceiverPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SpeechReceiverPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SpeechReceiverPrx ice_preferSecure(boolean b)
    {
        return (SpeechReceiverPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SpeechReceiverPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SpeechReceiverPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SpeechReceiverPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SpeechReceiverPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SpeechReceiverPrx ice_collocationOptimized(boolean b)
    {
        return (SpeechReceiverPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SpeechReceiverPrx ice_twoway()
    {
        return (SpeechReceiverPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SpeechReceiverPrx ice_oneway()
    {
        return (SpeechReceiverPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SpeechReceiverPrx ice_batchOneway()
    {
        return (SpeechReceiverPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SpeechReceiverPrx ice_datagram()
    {
        return (SpeechReceiverPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SpeechReceiverPrx ice_batchDatagram()
    {
        return (SpeechReceiverPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SpeechReceiverPrx ice_compress(boolean co)
    {
        return (SpeechReceiverPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SpeechReceiverPrx ice_timeout(int t)
    {
        return (SpeechReceiverPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SpeechReceiverPrx ice_connectionId(String connectionId)
    {
        return (SpeechReceiverPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/

    static String ice_staticId()
    {
        return "::whisperIced::SpeechReceiver";
    }
}
